# Generated by Django 4.2.4 on 2024-02-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['create_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Setapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startworktime', models.TimeField(null=True, verbose_name='Начало рабочего дня')),
                ('endtworktime', models.TimeField(null=True, verbose_name='Конец рабочего дня')),
                ('timestap', models.IntegerField(null=True, verbose_name='Шаг планирования в минутах')),
                ('numofroom', models.IntegerField(null=True, verbose_name='Количество комнат')),
                ('roomlist', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetplan.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметры',
                'ordering': ['startworktime', 'endtworktime', 'timestap', 'numofroom', 'user', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meet', models.DateField(verbose_name='Дата встречи')),
                ('time_start', models.TimeField(verbose_name='Время начала встречи')),
                ('time_end', models.TimeField(verbose_name='Время окончания встречи')),
                ('quantity', models.IntegerField(verbose_name='Количество гостей')),
                ('option1', models.BooleanField(default=0)),
                ('option2', models.BooleanField(default=0)),
                ('planned', models.BooleanField(default=0, verbose_name='Запланирована')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetplan.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['date_meet', 'time_start', 'planned'],
            },
        ),
    ]
