# Generated by Django 4.2.4 on 2024-02-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, verbose_name='№')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('volume', models.IntegerField(null=True, verbose_name='Кол-во мест')),
                ('option1', models.BooleanField(default=0, verbose_name='Опция 1')),
                ('option2', models.BooleanField(default=0, verbose_name='Опция 2')),
                ('plan', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Переговорка',
                'verbose_name_plural': 'Переговорки',
                'ordering': ['number', 'name', 'volume', 'option1', 'option2'],
            },
        ),
        migrations.AlterModelOptions(
            name='setapp',
            options={'ordering': ['startworktime', 'endtworktime', 'timestap', 'user', 'created_at'], 'verbose_name': 'Параметры', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='option1',
            field=models.BooleanField(default=0, verbose_name='Опция 1'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='option2',
            field=models.BooleanField(default=0, verbose_name='Опция 2'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='quantity',
            field=models.IntegerField(verbose_name='Участников'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetplan.user', verbose_name='Автор'),
        ),
    ]
