# Generated by Django 4.2.4 on 2024-02-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetplan', '0002_rooms_alter_setapp_options_alter_meeting_option1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setapp',
            new_name='Param',
        ),
    ]
