# Generated by Django 4.2.4 on 2024-02-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetplan', '0003_rename_setapp_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='plan',
            field=models.JSONField(null=True),
        ),
    ]
