# Generated by Django 4.2.4 on 2024-02-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetplan', '0004_alter_rooms_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['name', 'volume', 'option1', 'option2'], 'verbose_name': 'Переговорка', 'verbose_name_plural': 'Переговорки'},
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='number',
        ),
    ]
