# Generated by Django 4.2.4 on 2024-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetplan', '0005_alter_rooms_options_remove_rooms_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date_meet', 'time_start', 'status'], 'verbose_name': 'Встреча', 'verbose_name_plural': 'Встречи'},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='planned',
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='volume',
            field=models.IntegerField(verbose_name='Кол-во мест'),
        ),
    ]
