# Generated by Django 4.2.4 on 2024-03-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetplan', '0007_dateplan_remove_param_numofroom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateplan',
            options={'ordering': ['dateplan'], 'verbose_name': 'Дату', 'verbose_name_plural': 'Даты'},
        ),
        migrations.AlterField(
            model_name='dateplan',
            name='dateplan',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
